[package]
name = "integration"
version = "0.1.0"
authors = ["jprochazk <honza.spacir@gmail.com>"]
edition = "2018"

[dependencies]
packet = { package = "packet-rs", git = "https://github.com/EverCrawl/packet-rs.git", branch = "master" }

[workspace]